# Generated by Django 4.2.4 on 2023-09-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="topic",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
