# Generated by Django 4.2.4 on 2023-08-19 17:12

from django.db import migrations, models
import server.models
import server.validator


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_category_icon_alter_server_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to=server.models.server_banner_upload_path
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.server_icon_upload_path,
                validators=[
                    server.validator.validate_icon_image_size,
                    server.validator.validate_image_file_exstension,
                ],
            ),
        ),
    ]
